version: '2.1'

services:
  f10:
    image: f10
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    restart: always
    command: node --inspect index.js
